### ISSUE TITLE
Exception during update with python 2.7 and UTF-8 path in contents file

### ISSUE THREAD

**Issue by doctaweeks** [gentoo/webapp-config#4]
webapp-config exits with the exception below during an update where an entry in the contents file contains a non-ASCII character. Workaround: Running using python 3+ does not exhibit the same problem.

Traceback (most recent call last):
  File "/usr/lib/python-exec/python2.7/webapp-config", line 42, in <module>
    main()
  File "/usr/lib/python-exec/python2.7/webapp-config", line 39, in main
    config.run()
  File "/usr/lib64/python2.7/site-packages/WebappConfig/config.py", line 1501, in run
    content.read()
  File "/usr/lib64/python2.7/site-packages/WebappConfig/content.py", line 212, in read
    + line_split[3]] = line_split
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 27: ordinal not in range(128)

**Comment by wapolinar** [comment]
I also experienced that while upgrading a package.
Do you have any nice method to recover from this without a reinstall?

I actually had this issue with python 3.4:

```
  File "/usr/lib/python-exec/python3.4/webapp-config", line 42, in <module>
    main()
  File "/usr/lib/python-exec/python3.4/webapp-config", line 39, in main
    config.run()
  File "/usr/lib64/python3.4/site-packages/WebappConfig/config.py", line 1509, in run
    self.config.get('USER', 'pvr'))
  File "/usr/lib64/python3.4/site-packages/WebappConfig/server.py", line 130, in upgrade
    self.install(True)
  File "/usr/lib64/python3.4/site-packages/WebappConfig/server.py", line 283, in install
    self.__ebuild.show_postupgrade(self)
  File "/usr/lib64/python3.4/site-packages/WebappConfig/ebuild.py", line 130, in show_postupgrade
    self.show_post(filename = 'postupgrade-en.txt', ptype = 'upgrade', server = server)
  File "/usr/lib64/python3.4/site-packages/WebappConfig/ebuild.py", line 91, in show_post
    post_instructions = open(post_file).readlines()
  File "/usr/lib64/python3.4/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 388: ordinal not in range(128)
```

**Comment by hydrapolic** [comment]
Same issue.
